# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG NUXT_PUBLIC_SITE_URL=https://lasrikas.com

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG NUXT_PUBLIC_SITE_URL=https://lasrikas.com

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL

COPY --from=builder /app/.output /app/.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
